export const homeObjOne = [
  {
    id: "greenpoint",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: "Bootcamp Project",
    headline: "GreenPoint",
    description: "Keep track of your sustainable activities.",
    buttonLabel: "Get started now!",
    imgStart: false,
    img: require("../../assets/images/svg-3.svg"),
    alt: "Car",
    dark: true,
    dark2: false,
    primary: true,
    darkText: false,
    repoLink: "https://github.com/aaronclimbs/greenpoint",
    liveLink: "https://glacial-peak-greenpoint.herokuapp.com/",
    screenshots: [
      require("../../assets/images/GreenpointFAQ.png"),
      require("../../assets/images/GreenpointHomepage.png"),
    ],
    stack: [
      "MongoDB",
      "ReactJS",
      "ES6",
      "HTML5",
      "CSS3",
      "JWT",
      "React-bootstrap",
    ],
  },
  {
    id: "meiplaw",
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: "Freelance/Work Project",
    headline: "Maddox Edwards",
    description: "A boutique IP law firm in Washington, DC",
    buttonLabel: "Defend your IP.",
    imgStart: true,
    img: require("../../assets/images/svg-4.svg"),
    alt: "Car",
    dark: false,
    dark2: false,
    primary: false,
    darkText: false,
    repoLink: "",
    liveLink: "https://www.meiplaw.com",
    // screenshots: [require("../../assets/images/MeiplawCover.png"), require("../../assets/images/MeiplawCases.png")],
    stack: ["TailwindCSS, ReactJS, Wordpress, GraphQL, ES6"],
  },
  {
    id: "flexpace",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: "Bootcamp Project",
    headline: "Flexspace",
    description: "Don't leave those conference rooms unused!",
    buttonLabel: "Rent your rooms now.",
    imgStart: false,
    img: require("../../assets/images/svg-1.svg"),
    alt: "Car",
    dark: true,
    dark2: false,
    primary: true,
    darkText: false,
    repoLink: "https://github.com/aaronclimbs/flexspace",
    liveLink: "https://gwbootcampflexspace.heroku app.com/",
    screenshots: [
      require("../../assets/images/FlexspaceCover2.png"),
      require("../../assets/images/FlexspaceSignup.png"),
    ],
    stack: [
      "Node.js",
      "ES6",
      "HTML5",
      "CSS3",
      "PassportJS",
      "Express",
      "SQL",
      "Sequelize",
      "EJS",
    ],
  },
  {
    id: "herbal",
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: "Freelance",
    headline: "Herbal Remedy Repository",
    description:
      "A comprehensive repository of most herbal remedies and their uses.",
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../assets/images/svg-2.svg"),
    alt: "Car",
    dark: false,
    dark2: false,
    primary: false,
    darkText: true,
    repoLink: "",
    liveLink: "https://herbalremedyrepository.com",
    stack: ["NextJS", "ReactJS", "TailwindCSS"],
  },
];

export const techIcons = {
  NextJS: {
    img: require("../../assets/images/logos/NextJS.png"),
    name: "NextJS",
  },
  "Node.js": {
    img: require("../../assets/images/logos/Node.png"),
    name: "Node.js",
  },
  ES6: {
    img: require("../../assets/images/logos/ES6.png"),
    name: "ES6",
  },
  HTML5: {
    img: require("../../assets/images/logos/HTML5.png"),
    name: "HTML5",
  },
  CSS3: {
    img: require("../../assets/images/logos/CSS3.png"),
    name: "CSS3",
  },
  PassportJS: {
    img: require("../../assets/images/logos/PassportJS.png"),
    name: "PassportJS",
  },
  Express: {
    img: require("../../assets/images/logos/Express.png"),
    name: "Express",
  },
  SQL: {
    img: require("../../assets/images/logos/SQL.png"),
    name: "SQL",
  },
  Sequelize: {
    img: require("../../assets/images/logos/Sequelize.png"),
    name: "Sequelize",
  },
  EJS: {
    img: require("../../assets/images/logos/EJS.png"),
    name: "EJS",
  },
  TailwindCSS: {
    img: require("../../assets/images/logos/TailwindCSS.png"),
    name: "TailwindCSS",
  },
  "Styled-components": {
    img: require("../../assets/images/logos/Styled.png"),
    name: "Styled-components",
  },
  GraphQL: {
    img: require("../../assets/images/logos/GraphQL.png"),
    name: "GraphQL",
  },
  MongoDB: {
    img: require("../../assets/images/logos/MongoDB.png"),
    name: "MongoDB",
  },
  Mongoose: {
    img: require("../../assets/images/logos/Mongoose.png"),
    name: "Mongoose",
  },
  Wordpress: {
    img: require("../../assets/images/logos/Wordpress.png"),
    name: "Wordpress",
  },
  ReactJS: {
    img: require("../../assets/images/logos/ReactJS.png"),
    name: "ReactJS",
  },
  JWT: {
    img: require("../../assets/images/logos/JWT.png"),
    name: "JSONWebTokens",
  },
  Bootstrap: {
    img: require("../../assets/images/logos/Bootstrap.png"),
    name: "Bootstrap",
  },
};
