export const homeObjOne = [
  {
    id: "greenpoint",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: "Bootcamp Project",
    headline: "GreenPoint",
    description:
      "Keep track of your sustainable activities.",
    buttonLabel: "Get started now!",
    imgStart: false,
    img: require("../../assets/images/svg-3.svg"),
    alt: "Car",
    dark: true,
    dark2: false,
    primary: true,
    darkText: false,
    repoLink: "https://github.com/aaronclimbs/greenpoint",
    liveLink: "https://glacial-peak-greenpoint.herokuapp.com/",
    screenshots: [require("../../assets/images/GreenpointFAQ.png"), require("../../assets/images/GreenpointHomepage.png")]
  },
  {
    id: "meiplaw",
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: "Freelance/Work Project",
    headline: "Maddox Edwards",
    description:
      "A boutique IP law firm in Washington, DC",
    buttonLabel: "Defend your IP.",
    imgStart: true,
    img: require("../../assets/images/svg-4.svg"),
    alt: "Car",
    dark: false,
    dark2: false,
    primary: false,
    darkText: false,
    repoLink: "",
    liveLink: "https://www.meiplaw.com",
    // screenshots: [require("../../assets/images/MeiplawCover.png"), require("../../assets/images/MeiplawCases.png")]
  },
  {
    id: "flexpace",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: "Bootcamp Project",
    headline: "Flexspace",
    description:
      "Don't leave those conference rooms unused!",
    buttonLabel: "Rent your rooms now.",
    imgStart: false,
    img: require("../../assets/images/svg-1.svg"),
    alt: "Car",
    dark: true,
    dark2: false,
    primary: true,
    darkText: false,
    repoLink: "https://github.com/aaronclimbs/flexspace",
    liveLink: "https://gwbootcampflexspace.herokuapp.com/",
    screenshots: [require("../../assets/images/FlexspaceCover2.png"), require("../../assets/images/FlexspaceSignup.png")]
  },
  {
    id: "herbal",
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: "Freelance",
    headline: "Herbal Remedy Repository",
    description:
      "A comprehensive repository of most herbal remedies and their uses.",
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../assets/images/svg-2.svg"),
    alt: "Car",
    dark: false,
    dark2: false,
    primary: false,
    darkText: true,
    repoLink: "",
    liveLink: "https://herbalremedyrepository.com"
  },
];
